services:
  gazzetta-injest:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT_NAME: gazzetta-injest
    environment:
      GAZZETTA_FEEDS_URL: "https://www.gazzettaufficiale.it/rss/SG,https://www.gazzettaufficiale.it/rss/S1,https://www.gazzettaufficiale.it/rss/S2,https://www.gazzettaufficiale.it/rss/S3,https://www.gazzettaufficiale.it/rss/S4,https://www.gazzettaufficiale.it/rss/S5,https://www.gazzettaufficiale.it/rss/P2"
      GAZZETTA_REDIS_URL: "redis://redis:6379"
      GAZZETTA_NEW_ARTICLE_TASK_QUEUE: "article-task-queue"
      RUST_LOG: "info"
    depends_on:
      - redis
  gazzetta-server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT_NAME: gazzetta-server
    environment:
      GAZZETTA_REDIS_URL: "redis://redis:6379"
      GAZZETTA_NEW_ARTICLE_TASK_QUEUE: "article-task-queue"
      GAZZETTA_NOTFIY_TASK_QUEUE: "notify-task-queue"
      SEARCH_KEYWORDS: "ecobonus,rottamazione,rottamare,rottamando,incentivi,incentivo,g/km,kg/km"
      RUST_LOG: "info"
    depends_on:
      - redis
  gazzetta-telegram:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT_NAME: gazzetta-telegram
    environment:
      GAZZETTA_REDIS_URL: "redis://redis:6379"
      GAZZETTA_NOTFIY_TASK_QUEUE: "notify-task-queue"
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHAT_ID: ""
      RUST_LOG: "info"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5